Sodium exception was caught
Medology/laravel-sodium pull request #13
Opened 2020-09-04 13:18 UTC by rad8329

**Method:**

**Expected Behavior:**

**Actual Result:**

**Cause:**

**Solution:**

**Customer Impact (for #releasenotes):**

**QA Notes (How to set up system for manual testing)**

2020-09-04 14:09 UTC, fortoulrodolfo requested changes

2020-09-04 14:09 UTC, fortoulrodolfo commented on src/Contracts/SodiumService.php
> +     * @throws SodiumException
Please add a description when this exception is thrown

2020-09-08 12:02 UTC, rashidsaf requested changes

2020-09-08 12:02 UTC, rashidsaf commented on src/Services/SodiumService.php
> +        } catch (DecryptException | KeyNotFoundException | MalformationException | SodiumException $e) {
I think swallowing all these exceptions is not appropriate here. We should let these to thrown and the user of this package should deal with the Exceptions. For example, making this change will break STDCheck logging unencrypted value on Model . `app/Model/EncryptedModel.php:276`

And of the projects that are using this Sodium package should approach this differently. For example, if the data coming from a Request then we can validate them to filter the malformed values. And for the Model side, we should always keep logging the malformed information to be alert to prevent patients data to be lost.

Creating all the validations on STDCheck and other projects is out of the scope of this issue. But issue can be created after some investigation

2020-09-08 12:31 UTC, rad8329 commented on src/Services/SodiumService.php
> +        } catch (DecryptException | KeyNotFoundException | MalformationException | SodiumException $e) {
Totally agreed with you.

2020-09-08 15:24 UTC, BKorenek requested changes

2020-09-08 15:24 UTC, BKorenek commented on tests/ServiceTest.php
>          $decryptedValue = $service->decryptValueByNonce($encryptedValue, $nonce);
We should probably go ahead and migrate this into the proper directory since we are here. Naming convention for tests follow the app directory structure. So if you are testing SodiumService it would be in `tests/Unit/app/services/SodiumServer` or whatever

2020-09-08 18:20 UTC, rad8329 commented
I will move this to a better solution on `STDcheck` repository, there we could keep logging the malformed data information. 
So this PR could be taken to address Brandon's and Rashid's CR, but it will unrelated to the original issue, so please let me know if I need to create a new PR to address those CR.

2020-09-08 19:01 UTC, PayneWheat requested changes

2020-09-08 19:01 UTC, PayneWheat commented on tests/ServiceTest.php
> +        $this->assertNull($decryptedValue);
Following Rashid's suggestion above, we can just assert the exception is thrown.
```suggestion

        $this->expectException(SodiumException::class);

        $decryptedValue = $service->decryptValueByNonce($wrongEncryptedValue, $nonce);
```

2020-10-08 19:03 UTC, rad8329 commented
Closed due to the solution was proposed in the PR  [11244](https://github.com/Medology/stdcheck.com/pull/11244) (`STDcheck` repository) and approved.

2020-10-08 19:03 UTC, closed without merging