Fix submodules was updated without updating project accordingly
Medology/laravel-sodium pull request #34
Opened 2021-09-30 15:24 UTC by Chekote

Problem:
The new submodules has switched to using a custom-php-cs-fixer composer package. The project's submodules was updated but the package was not added.

Fix:
Update the project to include the new package, remove unnecessary files, and apply the fixer.

2021-09-30 19:26 UTC, jose-ochoa requested changes
Shouldn't we just rename this dir to `php` if it has nothing specific to version?

![image](https://user-images.githubusercontent.com/16085034/135518105-1e68fad9-fcbb-474d-b5f8-e4ad85fd9f79.png)

2021-09-30 19:34 UTC, Chekote commented
@jose-ochoa I considered doing that, but then I noticed that there was a difference between the 7.1 and 7.2+ images:

It takes a build arg that allows you to build any PHP version, but the Dockerfile is not compatible with anything below 7.2 because Sodium was only included by default in 7.2+. If you build the image with 7.1 then it will fail the tests because the package is missing.

If I renamed it to PHP, I would need to put that information somewhere. I wouldn't want someone to waste a bunch of time trying to build it with something less than 7.2 and spend time trying to workout why tests are failing.

2021-09-30 19:54 UTC, jose-ochoa submitted a review, later dismissed

2021-10-01 11:20 UTC, rashidsaf approved these changes

2021-10-01 11:20 UTC, rashidsaf commented on bin/linux-sed
> +. "$ROOT"/docker/lib/images.sh
If we don't use the `$ALPINE_IMAGE`. Then no need to import `images.sh`

2021-10-01 13:01 UTC, DevanTarunKumar submitted a review, later dismissed

2021-10-01 13:17 UTC, jose-ochoa approved these changes

2021-10-04 11:12 UTC, rashidsaf approved these changes

2021-10-04 12:12 UTC, merged